project:
  artifactId: sb-kong-poc
  name: sb-kong-poc
  version: 1.0.0
  description: The POC application to test kong for oauth process.


# Exposing all the actuator end points (Spring 2.0) #
management:
  endpoints:
    web:
      exposure:
        include:
          '*'

  # Exposing the restart & shutdown endpoint
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true

# For Spring Actuator /info endpoint
info:
  artifact: ${project.artifactId}
  name: ${project.name}
  description: ${project.description}
  version: ${project.version}

# Spring
spring:
  application:
    name: sb-kong-poc


# use a HTTP port 8080
server:
  port: 8085

---
spring:
  profiles: stage

server:
  port: 8085


---
spring:
  profiles: prod

server:
  port: 8085


